/**
 * @module features/tips/tips.data
 * @description Curated database of 50+ actionable carbon reduction tips.
 * Each tip includes estimated annual savings in kg CO₂e.
 */

import type { ReductionTip } from '@carbon/shared';

/** Complete collection of actionable reduction tips */
export const TIPS_DATABASE: Omit<ReductionTip, 'id'>[] = [
  // ─── Travel Tips ─────────────────────────────────────────
  {
    title: 'Switch to Public Transit',
    description: 'Replace car commutes with bus or train. Public transport produces 80% fewer emissions per passenger-kilometer than driving alone.',
    category: 'travel',
    impactLevel: 'high',
    estimatedSavingsKgPerYear: 2400,
    iconName: 'Train',
  },
  {
    title: 'Work from Home 2 Days a Week',
    description: 'Remote work eliminates commuting emissions entirely on those days. Even 2 days saves nearly 1 tonne of CO₂e annually for average commuters.',
    category: 'travel',
    impactLevel: 'high',
    estimatedSavingsKgPerYear: 960,
    iconName: 'Home',
  },
  {
    title: 'Choose Electric or Hybrid',
    description: 'If you must drive, switch to an EV. Electric vehicles produce 50–70% fewer lifecycle emissions than petrol cars.',
    category: 'travel',
    impactLevel: 'high',
    estimatedSavingsKgPerYear: 1800,
    iconName: 'Zap',
  },
  {
    title: 'Carpool to Work',
    description: 'Sharing rides with just one colleague halves your per-person driving emissions. Apps like BlaBlaCar make this effortless.',
    category: 'travel',
    impactLevel: 'medium',
    estimatedSavingsKgPerYear: 1200,
    iconName: 'Users',
  },
  {
    title: 'Take the Train Instead of Flying',
    description: 'For trips under 800 km, trains produce 85% fewer emissions than flights. High-speed rail often takes similar door-to-door time.',
    category: 'travel',
    impactLevel: 'high',
    estimatedSavingsKgPerYear: 1500,
    iconName: 'TrainTrack',
  },
  {
    title: 'Cycle for Short Trips',
    description: 'Replace car trips under 5 km with cycling. This eliminates emissions entirely and improves cardiovascular health.',
    category: 'travel',
    impactLevel: 'medium',
    estimatedSavingsKgPerYear: 600,
    iconName: 'Bike',
  },
  {
    title: 'Maintain Optimal Tire Pressure',
    description: 'Under-inflated tires increase fuel consumption by 3–5%. Check pressure monthly and keep tires at the manufacturer-recommended PSI.',
    category: 'travel',
    impactLevel: 'low',
    estimatedSavingsKgPerYear: 120,
    iconName: 'Gauge',
  },
  {
    title: 'Fly Economy Class',
    description: 'Business class has 3× the carbon footprint of economy due to seat space. Choose economy for a smaller personal impact.',
    category: 'travel',
    impactLevel: 'medium',
    estimatedSavingsKgPerYear: 800,
    iconName: 'PlaneTakeoff',
  },
  {
    title: 'Reduce Air Travel by 50%',
    description: 'One long-haul return flight equals nearly a year of driving. Use video conferencing for business and explore local destinations.',
    category: 'travel',
    impactLevel: 'high',
    estimatedSavingsKgPerYear: 3000,
    iconName: 'PlaneOff',
  },
  {
    title: 'Practice Eco-Driving',
    description: 'Smooth acceleration, maintaining speed limits, and using cruise control can reduce fuel use by 15–20%.',
    category: 'travel',
    impactLevel: 'low',
    estimatedSavingsKgPerYear: 350,
    iconName: 'Leaf',
  },

  // ─── Energy Tips ─────────────────────────────────────────
  {
    title: 'Switch to a Green Energy Tariff',
    description: 'Renewable energy tariffs source electricity from wind, solar, and hydro. This can slash your electricity emissions by up to 100%.',
    category: 'energy',
    impactLevel: 'high',
    estimatedSavingsKgPerYear: 1500,
    iconName: 'Sun',
  },
  {
    title: 'Install a Smart Thermostat',
    description: 'Smart thermostats learn your schedule and reduce heating by 10–15%. Nest and Hive pay for themselves in energy savings within a year.',
    category: 'energy',
    impactLevel: 'medium',
    estimatedSavingsKgPerYear: 450,
    iconName: 'Thermometer',
  },
  {
    title: 'Upgrade to LED Lighting',
    description: 'LEDs use 80% less electricity than incandescent bulbs and last 25× longer. Replace all bulbs in your home for instant savings.',
    category: 'energy',
    impactLevel: 'medium',
    estimatedSavingsKgPerYear: 200,
    iconName: 'Lightbulb',
  },
  {
    title: 'Lower Thermostat by 2°C',
    description: 'Reducing your heating by just 2°C can cut heating emissions by 10% without noticeable comfort loss. Layer up instead.',
    category: 'energy',
    impactLevel: 'medium',
    estimatedSavingsKgPerYear: 300,
    iconName: 'ThermometerSnowflake',
  },
  {
    title: 'Insulate Your Home',
    description: 'Proper loft and wall insulation can reduce heating needs by 30–40%. Government grants often cover installation costs.',
    category: 'energy',
    impactLevel: 'high',
    estimatedSavingsKgPerYear: 1200,
    iconName: 'Building',
  },
  {
    title: 'Use Cold Water for Laundry',
    description: 'Washing clothes at 30°C instead of 60°C reduces energy per wash by 57%. Modern detergents work just as well in cold water.',
    category: 'energy',
    impactLevel: 'low',
    estimatedSavingsKgPerYear: 100,
    iconName: 'Droplets',
  },
  {
    title: 'Unplug Standby Electronics',
    description: 'Standby power ("vampire draw") accounts for 5–10% of household electricity. Use smart power strips to cut power when devices sleep.',
    category: 'energy',
    impactLevel: 'low',
    estimatedSavingsKgPerYear: 150,
    iconName: 'Unplug',
  },
  {
    title: 'Install Solar Panels',
    description: 'Residential solar can offset 80–100% of electricity consumption. With falling costs, payback periods are now under 7 years.',
    category: 'energy',
    impactLevel: 'high',
    estimatedSavingsKgPerYear: 2000,
    iconName: 'SunDim',
  },
  {
    title: 'Use a Heat Pump',
    description: 'Air-source heat pumps are 3–4× more efficient than gas boilers. They can reduce heating emissions by 60–75%.',
    category: 'energy',
    impactLevel: 'high',
    estimatedSavingsKgPerYear: 1800,
    iconName: 'Wind',
  },
  {
    title: 'Air Dry Your Clothes',
    description: 'Tumble dryers are one of the most energy-hungry appliances. Line-drying saves ~3 kWh per load.',
    category: 'energy',
    impactLevel: 'low',
    estimatedSavingsKgPerYear: 180,
    iconName: 'Shirt',
  },

  // ─── Diet Tips ───────────────────────────────────────────
  {
    title: 'Reduce Red Meat to Once a Week',
    description: 'Beef produces 27 kg CO₂e per kg — 20× more than legumes. Cutting to once a week saves over 1 tonne annually.',
    category: 'diet',
    impactLevel: 'high',
    estimatedSavingsKgPerYear: 1100,
    iconName: 'Beef',
  },
  {
    title: 'Try "Meatless Mondays"',
    description: 'Replacing meat with plant-based meals one day a week is an easy first step. It saves roughly 200 kg CO₂e per year.',
    category: 'diet',
    impactLevel: 'medium',
    estimatedSavingsKgPerYear: 200,
    iconName: 'Salad',
  },
  {
    title: 'Choose Chicken Over Beef',
    description: 'Chicken produces 4× fewer emissions than beef per kg. Swapping beef for chicken in just half your meals makes a huge difference.',
    category: 'diet',
    impactLevel: 'medium',
    estimatedSavingsKgPerYear: 600,
    iconName: 'Drumstick',
  },
  {
    title: 'Eat Seasonal & Local Produce',
    description: 'Out-of-season produce often arrives by air freight (50× more emissions than shipping). Shop at farmers\' markets for seasonal picks.',
    category: 'diet',
    impactLevel: 'medium',
    estimatedSavingsKgPerYear: 400,
    iconName: 'Apple',
  },
  {
    title: 'Reduce Food Waste by 50%',
    description: 'The average household wastes 30% of food purchased. Plan meals, use leftovers, and compost scraps to halve your waste.',
    category: 'diet',
    impactLevel: 'high',
    estimatedSavingsKgPerYear: 800,
    iconName: 'Trash2',
  },
  {
    title: 'Switch to Plant-Based Milk',
    description: 'Oat milk produces 80% fewer emissions than dairy milk. It also uses 60% less energy and 80% less land.',
    category: 'diet',
    impactLevel: 'low',
    estimatedSavingsKgPerYear: 150,
    iconName: 'GlassWater',
  },
  {
    title: 'Grow Your Own Herbs & Vegetables',
    description: 'Even a small balcony garden eliminates transport and packaging emissions for herbs, salad greens, and tomatoes.',
    category: 'diet',
    impactLevel: 'low',
    estimatedSavingsKgPerYear: 50,
    iconName: 'Sprout',
  },
  {
    title: 'Choose Legumes as Protein',
    description: 'Lentils and beans produce just 0.9 kg CO₂e per kg — 30× less than beef. They\'re also cheaper and packed with fiber.',
    category: 'diet',
    impactLevel: 'medium',
    estimatedSavingsKgPerYear: 500,
    iconName: 'Bean',
  },
  {
    title: 'Cut Dairy Consumption by Half',
    description: 'Cheese production is surprisingly carbon-intensive (13.5 kg CO₂e/kg). Halving dairy intake makes a meaningful difference.',
    category: 'diet',
    impactLevel: 'medium',
    estimatedSavingsKgPerYear: 350,
    iconName: 'Milk',
  },
  {
    title: 'Adopt a Flexitarian Diet',
    description: 'Flexitarians eat mostly plants with occasional meat. This dietary pattern reduces food emissions by 40% compared to average diets.',
    category: 'diet',
    impactLevel: 'high',
    estimatedSavingsKgPerYear: 1500,
    iconName: 'Vegan',
  },

  // ─── General Tips ────────────────────────────────────────
  {
    title: 'Track Your Footprint Monthly',
    description: 'What gets measured gets managed. Regular tracking with this tool helps identify your biggest emission sources and celebrate reductions.',
    category: 'general',
    impactLevel: 'medium',
    estimatedSavingsKgPerYear: 500,
    iconName: 'BarChart3',
  },
  {
    title: 'Offset Unavoidable Emissions',
    description: 'For emissions you can\'t eliminate (like essential flights), invest in verified carbon offset projects (Gold Standard or Verra).',
    category: 'general',
    impactLevel: 'medium',
    estimatedSavingsKgPerYear: 0,
    iconName: 'TreePine',
  },
  {
    title: 'Influence Your Workplace',
    description: 'Advocate for sustainability policies at work: remote options, green energy contracts, and reduced business travel.',
    category: 'general',
    impactLevel: 'high',
    estimatedSavingsKgPerYear: 2000,
    iconName: 'Briefcase',
  },
  {
    title: 'Buy Less, Choose Well',
    description: 'Every product has embedded carbon. Buying fewer, higher-quality items that last longer significantly reduces your consumption footprint.',
    category: 'general',
    impactLevel: 'medium',
    estimatedSavingsKgPerYear: 700,
    iconName: 'ShoppingBag',
  },
  {
    title: 'Support Climate-Positive Brands',
    description: 'Choose companies committed to net-zero targets and transparent carbon reporting. Your purchasing power drives corporate change.',
    category: 'general',
    impactLevel: 'low',
    estimatedSavingsKgPerYear: 300,
    iconName: 'Heart',
  },
];
